name: haproxy-lool
version: 1.7.9
summary: The Reliable, High Performance TCP/HTTP Load Balancer
description: |
  HAProxy is a free, very fast and reliable solution offering high
  availability, load balancing, and proxying for TCP and HTTP-based
  applications. It is particularly suited for very high traffic web sites and
  powers quite a number of the world's most visited ones. Over the years it has
  become the de-facto standard opensource load balancer, is now shipped with
  most mainstream Linux distributions, and is often deployed by default in
  cloud platforms.
grade: stable
confinement: strict

apps:
  haproxy:
    command: bin/haproxy
    plugs: [network, network-bind]
  haproxyd:
    command: bin/haproxyd
    daemon: simple
    plugs: [network, network-bind]

parts:
  haproxy:
    plugin: make
    source: http://www.haproxy.org/download/1.7/src/haproxy-1.7.9.tar.gz
    build-packages: [gcc]
    make-parameters: [TARGET=generic]
    organize:
      usr/local/sbin/haproxy: bin/haproxy
    prime: [bin/haproxy]
  wrapper:
    plugin: dump
    source: glue

